### ISSUE TITLE
find_program() deduces wrong ld version and enables incompatible flag on older arm-none-eabi-ld

### ISSUE THREAD

**Issue by ScrelliCopter** [LunarLambda/sdk-seven#2]
Relevant line:
https://github.com/LunarLambda/sdk-seven/blob/d4ea3edb9172ad474077263a71520a2e215fa1eb/meson.build#L35

  

When using an older build of arm-none-eabi gcc, meson appears to grab the version of the entire toolchain instead of ld's version:
```
Program arm-none-eabi-ld found: YES 10.3
```

Here's the raw `--version` output of ld:
```
$ arm-none-eabi-ld --version
GNU ld (GNU Arm Embedded Toolchain 10.3-2021.07) 2.36.1.20210621
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

Which leads to linker errors when trying to compile the examples:
```
[30/35] Linking target examples/vsync-callback/example-vsync-callback.elf
FAILED: examples/vsync-callback/example-vsync-callback.elf 
arm-none-eabi-gcc  -o examples/vsync-callback/example-vsync-callback.elf examples/vsync-callback/example-vsync-callback.elf.p/src_main.c.o -Wl,--as-needed -Wl,--no-undefined -mthumb -Wl,--gc-sections -specs=nano.specs -Wl,--no-warn-rwx-segments -Wl,--start-group libseven/libseven.a minrt/libminrt_rom.a -Wl,--end-group -Wl,-Map,example-vsync-callback.map -specs=<snip>/sdk-seven-0.9.0/minrt/lib/nocrt0.specs -Trom.ld -L<snip>/sdk-seven-0.9.0/minrt/lib/ldscripts
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: unrecognized option '--no-warn-rwx-segments'
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
```

Commenting the whole test out causes everything to compile correctly.

  

A much more recent toolchain is able to be detected properly:
```
Program arm-none-eabi-ld found: YES 2.39
```

And here's the `--version` output for that chain's ld:
```
$ arm-none-eabi-ld --version
GNU ld (GNU Binutils) 2.39
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

Unfortunately I can't verify this version links correctly because of earlier compiler errors that I suspect are bugs in this toolchain's gcc that aren't relevant to this issue, but I suspect it would given the flag is intended for this version.

  

The issue seems to be that meson's `find_program()` assumes the first text that looks like a valid version is the actual reported version, an assumption which breaks on builds of gcc which print the toolchain version before the individual program version. I'm not familiar enough with meson to know how to fix or work around this in a way that's PR worthy.

**Comment by LunarLambda** [comment]
The current find_program approach is a hack for many reasons:

1. meson assumes the first version number thing is the version, always

2. find_program could return a different version of arm-none-eabi-ld than the compiler actually uses

3. meson has a has_link_argument function for this exact reason, but it doesn't work on arm-none-eabi: https://github.com/mesonbuild/meson/issues/10957

The "proper" solution until 3. is fixed would be to use `run_command()` or `cc.links()` to figure out availability.

I will produce a fix tomorrow, it's currently 3 am.

Relatedly, GNU ARM Embedded Toolchain 10.3 is known to have other problems as well, so at any rate, I suggest updating. The downloads for the toolchain have moved since 10.3, the latest version is found here: https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

**Comment by LunarLambda** [comment]
If you need a fix right *now*, changing the find_program call to pass `version: ['>=2.39', '<3.0']` instead of `version: '>=2.39'` should be good enough.

**Comment by ScrelliCopter** [comment]
Appreciate the quick response, I gave that newer toolchain a shot and sure enough it works just fine. I'll keep the VM with the older toolchain around just in case it's needed for testing but if it's likely to have problems anyway I'll probably just stick with the latest.

**Comment by LunarLambda** [comment]
I just pushed https://github.com/LunarLambda/sdk-seven/commit/d6b6d42b2deb2139d204da33a77303b0569eb978 too. I'm not sure how future-proof it is, but I don't expect it to break too quickly

**Comment by ScrelliCopter** [comment]
Gave main a shot on both toolchains. The older one builds correctly now, although the test seems to false negative on the newer toolchain so it gets the `<...>.elf has a LOAD segment with RWX permissions` warning.
Better than not compiling obviously but probably still not desirable.

**Comment by ScrelliCopter** [comment]
I'm still not very familiar with meson but I think I managed to find why the flag isn't being enabled, the test is failing to link:
```
Running compile:
Working directory:  <snip>/sdk-seven/build/meson-private/tmp
Command line:  arm-none-eabi-gcc <snip>/sdk-seven/build/meson-private/tmp/testfile.c -o <snip>/sdk-seven/build/meson-private/tmp/output.exe -mcpu=arm7tdmi -mabi=aapcs -mfloat-abi=soft -D_FILE_OFFSET_BITS=64 -O0 -std=c99 -Wl,--no-warn-rwx-segments 

Code:
 int _exit(int) {} int main() {}
Compiler stdout:
 
Compiler stderr:
 /opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libc.a(libc_a-closer.o): in function `_close_r':
closer.c:(.text._close_r+0x18): undefined reference to `_close'
/opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libc.a(libc_a-lseekr.o): in function `_lseek_r':
lseekr.c:(.text._lseek_r+0x24): undefined reference to `_lseek'
/opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libc.a(libc_a-readr.o): in function `_read_r':
readr.c:(.text._read_r+0x24): undefined reference to `_read'
/opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libc.a(libc_a-sbrkr.o): in function `_sbrk_r':
sbrkr.c:(.text._sbrk_r+0x18): undefined reference to `_sbrk'
/opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /opt/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/lib/libc.a(libc_a-writer.o): in function `_write_r':
writer.c:(.text._write_r+0x24): undefined reference to `_write'
collect2: error: ld returned 1 exit status
```

**Comment by LunarLambda** [comment]
Darn. It worked with both of the toolchains I tried (devkitPro, Arch Linux repository)

Don't have a macOS machine to work with, but maybe the Linux build of the ARM GNU build will behave the same..

Give me another day to work it out, it's 5 am and I'm getting up for work soon

**Comment by LunarLambda** [comment]
Okay, can you try this:

```meson
ld_h = run_command(cc, '-Wl,--help', capture: true, check: false)

if ld_h.stdout().contains('--no-warn-rwx-segments')
  add_project_link_arguments('--no-warn-rwx-segments', language: 'c')
endif
```

Lacking any consistency between ARM toolchains, this is the only thing I can think of that should work regardless of what you're running.

**Comment by ScrelliCopter** [comment]
That works but I had to change `add_project_link_arguments('--no-warn-rwx-segments', language: 'c')` to `add_project_link_arguments('-Wl,--no-warn-rwx-segments', language: 'c')`
I'll give it a try on the older toolchain and report back.

**Comment by LunarLambda** [comment]
right, typo. my bad

**Comment by ScrelliCopter** [comment]
Yep, can confirm that works on 10.3 as well.

**Comment by LunarLambda** [comment]
Alright. Will close this when I push the fix. Thank you for your help

**Comment by LunarLambda** [comment]
https://github.com/LunarLambda/sdk-seven/commit/e6bb0dd4f1f7f6f43da1e2db3e3cb7ada531cc8b
